In [3]:
from keras.preprocessing.text import Tokenizer

samples = ['The cat sat on the mat.', 'The dog ate my homework.']

tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(samples)

sequences = tokenizer.texts_to_sequences(samples)

print(sequences)

one_hot_result = tokenizer.texts_to_matrix(samples, mode='binary')

print(one_hot_result)

word_index = tokenizer.word_index

print('token count: ', word_index)

[[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]
[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
token count:  {'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}


In [4]:
from keras.datasets import imdb
from keras import preprocessing

max_features = 10000
maxlen = 20

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)


# [65 16 38  2 88 12 16  2  5 16  2  2  2 32 15 16  2 19  2 32]
# Convert 2D tensor
x_train = preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen)

In [5]:
x_train.shape

(25000, 20)

In [6]:
from keras.models import Sequential
from keras.layers import Flatten,Dense,Embedding

model = Sequential()
# feature, dimention
model.add(Embedding(10000, 8 , input_length = maxlen))

model.add(Flatten())

model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='RMSprop', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 8)             80000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 161       
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________
None


In [7]:
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)


Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 1s 74us/step - loss: 0.6780 - acc: 0.5967 - val_loss: 0.6393 - val_acc: 0.6862
Epoch 2/10
20000/20000 [==============================] - 1s 59us/step - loss: 0.5607 - acc: 0.7443 - val_loss: 0.5364 - val_acc: 0.7270
Epoch 3/10
20000/20000 [==============================] - 1s 56us/step - loss: 0.4696 - acc: 0.7854 - val_loss: 0.5033 - val_acc: 0.7444
Epoch 4/10
20000/20000 [==============================] - 1s 55us/step - loss: 0.4247 - acc: 0.8079 - val_loss: 0.4931 - val_acc: 0.7532
Epoch 5/10
20000/20000 [==============================] - 1s 58us/step - loss: 0.3952 - acc: 0.8234 - val_loss: 0.4925 - val_acc: 0.7604
Epoch 6/10
20000/20000 [==============================] - 1s 60us/step - loss: 0.3720 - acc: 0.8365 - val_loss: 0.4951 - val_acc: 0.7620
Epoch 7/10
20000/20000 [==============================] - 1s 56us/step - loss: 0.3523 - acc: 0.8475 - val_loss: 0.5017 - val_acc